# All of the fields are optional, port will default to 8080

client_key = "client-key"
cors_hostnames = ["http://localhost", "https://example.com"]
allowed_keys = ["session:start", "session:end"]
port = 80
