name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ACCESS_KEY: p4ss

jobs:     
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust Nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
